version: '3.8'

volumes:
  postgres:

services:
  app:
    container_name: app
    build: 
      dockerfile: ./app/Dockerfile
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: postgres
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres